name: Nightly build

on:
  schedule:
    - cron: '0 0 * * *' # run at midnight UTC
  workflow_dispatch:

jobs:
  build-archetype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java SE 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Archetype
        run: mvn clean install --file archetype/pom.xml
        
      - name: Set up Java SE 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          
      - name: Set up Java SE 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17  

      - name: Run Archetype for EE 8 Web Profile, SE 8, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=8 -Druntime="tomee" -Ddocker=yes -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 8 Web Profile, SE 8, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=8 -Druntime="tomee" -Ddocker=no -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 9.1 Web Profile, SE 11, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=web -DjavaVersion=11 -Druntime="tomee" -Ddocker=yes -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 9.1 Web Profile, SE 11, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=web -DjavaVersion=11 -Druntime="tomee" -Ddocker=no -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 8 Web Profile, SE 11, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=11 -Druntime="tomee" -Ddocker=yes -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 8 Web Profile, SE 11, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=11 -Druntime="tomee" -Ddocker=no -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 9.1 Web Profile, SE 17, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=web -DjavaVersion=17 -Druntime="tomee" -Ddocker=yes -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 9.1 Web Profile, SE 17, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=9.1 -Dprofile=web -DjavaVersion=17 -Druntime="tomee" -Ddocker=no -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 8 Web Profile, SE 17, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=17 -Druntime="tomee" -Ddocker=yes -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee

      - name: Run Archetype for EE 8 Web Profile, SE 17, Tomee
        run: |
          mvn archetype:generate -DinteractiveMode=false -DaskForDefaultPropertyValues=false -DarchetypeGroupId=org.eclipse.starter -DarchetypeArtifactId=jakarta-starter -DarchetypeVersion=2.3.0-SNAPSHOT -DjakartaVersion=8 -Dprofile=web -DjavaVersion=17 -Druntime="tomee" -Ddocker=no -DoutputDirectory="app/tomee" -Dgoals="clean package"
          rm -rf app/tomee
  
  build-ui:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build UI
        run: mvn clean package --file ui/pom.xml
